import { useState, useEffect, useCallback } from 'react';
import { Card, Title, Text, Callout } from '@tremor/react';
import type { FleetReport } from './types';
import { FleetMetrics } from './FleetMetrics';
import { FleetTable } from './FleetTable';
import { TeamFilter } from './TeamFilter';

// Data source - static JSON file refreshed by Fleet Manager cron job
const FLEET_DATA_URL = '/fleet-status.json';
const REFRESH_INTERVAL = 60000; // 60 seconds

export function FleetDashboard() {
  const [data, setData] = useState<FleetReport | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [lastUpdated, setLastUpdated] = useState<Date | null>(null);
  const [teamFilter, setTeamFilter] = useState('all');

  const fetchData = useCallback(async () => {
    console.log('[FleetDashboard] Fetching data...');
    try {
      const response = await fetch(FLEET_DATA_URL);
      console.log('[FleetDashboard] Response:', response.status);

      if (!response.ok) {
        throw new Error(`Failed to fetch fleet status: ${response.status}`);
      }

      const report: FleetReport = await response.json();
      console.log('[FleetDashboard] Loaded:', report.total, 'sprites');

      setData(report);
      setError(null);
      setLastUpdated(new Date());
    } catch (err) {
      console.error('[FleetDashboard] Error:', err);
      setError(err instanceof Error ? err.message : 'Unknown error');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchData();

    // Set up auto-refresh
    const interval = setInterval(fetchData, REFRESH_INTERVAL);
    return () => clearInterval(interval);
  }, [fetchData]);

  if (loading) {
    return (
      <Card className="p-6">
        <div className="flex items-center justify-center py-12">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-500"></div>
          <span className="ml-3 text-gray-500">Loading fleet status...</span>
        </div>
      </Card>
    );
  }

  if (error) {
    return (
      <Callout title="Error Loading Fleet Status" color="red">
        <p>{error}</p>
        <p className="mt-2 text-sm">
          Make sure the fleet status JSON is available at <code>/fleet-status.json</code>.
          This file should be generated by running <code>fleet report -o public/fleet-status.json</code> on the N100 server.
        </p>
      </Callout>
    );
  }

  if (!data) {
    return (
      <Callout title="No Data" color="yellow">
        No fleet status data available.
      </Callout>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <Title>Fleet Status</Title>
          <Text>
            Last updated: {data.timestamp}
            {lastUpdated && (
              <span className="ml-2 text-gray-400">
                (fetched {lastUpdated.toLocaleTimeString()})
              </span>
            )}
          </Text>
        </div>
        <TeamFilter selectedTeam={teamFilter} onTeamChange={setTeamFilter} />
      </div>

      <FleetMetrics data={data} />

      {data.errors.length > 0 && (
        <Callout title={`${data.errors.length} Sprite Error${data.errors.length > 1 ? 's' : ''}`} color="red">
          <ul className="list-disc list-inside mt-2">
            {data.errors.map((err, idx) => (
              <li key={idx}>
                <strong>{err.sprite}</strong>: {err.status}
                {err.error && <span className="text-gray-400"> - {err.error}</span>}
              </li>
            ))}
          </ul>
        </Callout>
      )}

      <Card>
        <FleetTable sprites={data.sprites} teamFilter={teamFilter} />
      </Card>
    </div>
  );
}
